//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS1.user
{


    public partial class ChiTIetSanPham
    {

        /// <summary>
        /// ChiTietSanPham1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::DACS1.usercontrol.ChiTietSanPham ChiTietSanPham1;
    }
}
